export const businessGoals = [
  "Generate more leads",
  "Increase sales",
  "Improve customer support",
  "Reduce operational costs",
  "Automate repetitive work",
  "Improve customer experience",
  "Increase online visibility",
  "Improve SEO",
  "Improve branding",
  "Digitize manual processes",
  "Centralize company information",
  "Improve internal communication",
  "Increase employee productivity",
  "Collect analytics",
  "Scale operations",
  "Improve security",
  "Improve customer retention",
  "Generate quotations automatically",
  "Accept online payments",
  "Manage bookings",
  "Manage inventory",
  "Manage staff",
  "Manage projects",
];
