export const features = [
  "Authentication",
  "User Roles",
  "Admin Dashboard",
  "Analytics Dashboard",
  "Reporting",
  "Real-time Notifications",
  "Email Notifications",
  "SMS",
  "WhatsApp",
  "Live Chat",
  "Bookings",
  "Payments",
  "Mpesa",
  "Stripe",
  "PayPal",
  "Search",
  "Maps",
  "GPS",
  "Inventory",
  "Invoices",
  "PDF Export",
  "Excel Export",
  "Reports",
  "Image Upload",
  "Video Upload",
  "Document Upload",
  "AI Assistant",
  "Knowledge Base",
  "CRM",
  "CMS",
  "Blog",
  "Multi-language",
  "Dark Mode",
  "Offline Support",
  "Cloud Sync",
];
