export const industries = [
  "Construction",
  "Real Estate",
  "Healthcare",
  "Schools",
  "Universities",
  "Hotels",
  "Restaurants",
  "Law Firms",
  "Banks",
  "Insurance",
  "NGOs",
  "Government",
  "Transport",
  "Logistics",
  "Manufacturing",
  "Retail",
  "Wholesale",
  "Tourism",
  "Travel",
  "Agriculture",
  "E-commerce",
  "Beauty",
  "Fashion",
  "Fitness",
  "Entertainment",
  "Events",
  "Professional Services",
  "Startups",
  "Small Businesses",
  "Corporate Enterprises",
  "Nonprofits",
  "Personal Brands",
];

export const industryRecommendations = [
  { slug: "construction", label: "Construction", recommendation: ["Corporate Website", "Project Gallery", "Quote System", "SEO", "CRM"] },
  { slug: "real-estate", label: "Real Estate", recommendation: ["Property Listings", "CRM", "Booking System", "Payment Integration"] },
  { slug: "healthcare", label: "Healthcare", recommendation: ["Patient Portal", "Booking System", "Secure Forms", "Analytics"] },
  { slug: "education", label: "Education", recommendation: ["Student Portal", "Admission System", "CMS", "Parent Dashboard"] },
  { slug: "hospitality", label: "Hospitality", recommendation: ["Online Ordering", "Booking", "Delivery Integration", "Menu CMS"] },
  { slug: "fintech", label: "Fintech", recommendation: ["Secure Platform", "Payment Integration", "Mobile Support", "Analytics"] },
];
