export const services = [
  "Web Development",
  "Landing Pages",
  "Business Websites",
  "Corporate Websites",
  "Government Portals",
  "NGO Websites",
  "School Portals",
  "Hospital Websites",
  "Real Estate Websites",
  "Tourism Websites",
  "Booking Platforms",
  "Marketplaces",
  "E-commerce",
  "Learning Management Systems",
  "Membership Platforms",
  "Client Portals",
  "Employee Portals",
  "Dashboards",
  "Admin Systems",
  "CRM",
  "ERP",
  "Inventory Systems",
  "Fleet Management",
  "Construction Management",
  "Property Management",
  "Accounting Systems",
  "HR Systems",
  "Payroll",
  "Document Management",
  "Knowledge Bases",
  "AI Chatbots",
  "AI Voice Agents",
  "AI Sales Assistants",
  "AI Customer Support",
  "Workflow Automation",
  "Email Automation",
  "WhatsApp Automation",
  "CRM Automation",
  "Cloud Hosting",
  "DevOps",
  "API Development",
  "Payment Integrations",
  "Analytics",
  "Cybersecurity",
  "SEO",
  "Brand Identity",
  "Logo Design",
  "UI/UX",
  "Mobile Apps",
  "Desktop Applications",
];
